


server:
   port: 8080
   

spring.datasource.initialization-mode: always


spring.datasource.url: jdbc:postgresql://localhost:5432/postgres
spring.datasource.username: postgres
spring.datasource.password: root






 
